## DAB200 -- Graded Lab 3

In this lab, you will gain some experience in dealing with missing data and further practice converting non-numeric features in a dataset to numeric.

**Target**: to predict `Comb Unadj FE - Conventional Fuel`

**Data set**: make sure you use the data assigned to your group!

| Groups | Data set |
| :-: | :-: |
| 1-3 | veh14_missing.csv |
| 4-5 | veh15_missing.csv |
| 6-8 | veh16_missing.csv |
| 9-11 | veh17_missing.csv |
| 12-14 | veh18_missing.csv |
| 15-17 | veh19_missing.csv |

**Important Notes:**
- Use [Chapter 7](https://mlbook.explained.ai/bulldozer-intro.html) of the textbook as a **guide**:
     - you only need to use **random forest** models;
- Code submitted for this lab should be:
     - error free
         - to make sure this is the case, before submitting, close all Jupyter notebooks, exit Anaconda, reload the lab notebook and execute all cells
     - final code
         - this means that I don't want to see every piece of code you try as you work through this lab but only the final code; only the code that fulfills the objective
- Use the **out-of-bag score** to evaluate models
     - Read Section 5.2 carefully so that you use this method properly
     - The oob score that you provide should be the average of 10 runs
- Don't make assumptions!


### Part 0

Please provide the following information:
 - Group Number - 8
 - Group Members
     - Ardhra Santhosh (0858704)
     - Athulya Ajayan (0852788)
     - Joann Prathap (0859054)
     - Sree Vishnu Kaniyankandi (0856360)

     

### Part 1 - Create and evaluate an initial model

In this part you should: 
 - use Section 7.3 of the textbook as a guide, except:
     - use all of the data; and
     - use 150 decision trees in your random forest models
 - read in the data
 - isolate all numeric features from original data set
 - fill in any missing values with 0
 - create and evaluate a baseline model 

#### Code (10 marks)

In [4]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor



In [5]:
veh = pd.read_csv('veh16_missing.csv')
print(veh.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'veh16_missing.csv'

In [ ]:
veh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Eng Displ                          845 non-null    float64
 1   # Cyl                              1213 non-null   int64  
 2   Comb Unadj FE - Conventional Fuel  1213 non-null   object 
 3   # Gears                            1213 non-null   int64  
 4   Max Ethanol % - Gasoline           1187 non-null   float64
 5   Intake Valves Per Cyl              1213 non-null   int64  
 6   Exhaust Valves Per Cyl             1213 non-null   int64  
 7   Trans Creeper Gear                 1213 non-null   object 
 8   Unique Label?                      1136 non-null   object 
 9   Air Aspiration Method Desc         1213 non-null   object 
 10  Fuel Metering Sys Desc             1213 non-null   object 
 11  Cyl Deact?                         985 non-null    objec

In [ ]:
veh.loc[veh['Comb Unadj FE - Conventional Fuel'] == 'Mod','Comb Unadj FE - Conventional Fuel'] = 0
veh[ 'Comb Unadj FE - Conventional Fuel'] = veh['Comb Unadj FE - Conventional Fuel'].astype (float)

In [ ]:
num_veh = veh.select_dtypes(include=['number'])
num_veh

Eng Displ  # Cyl  Comb Unadj FE - Conventional Fuel  # Gears  \
0           NaN      4                            32.8729        6   
1           NaN      4                            41.5766        6   
2           1.8      4                            42.3624        6   
3           3.5      6                            29.3963        6   
4           NaN      6                            25.4694        6   
...         ...    ...                                ...      ...   
1208        NaN      8                            23.5520        8   
1209        5.0      8                            23.8378        8   
1210        3.3      6                            26.3588        6   
1211        2.0      4                            38.6792        6   
1212        2.7      4                            27.5097        6   

      Max Ethanol % - Gasoline  Intake Valves Per Cyl  Exhaust Valves Per Cyl  
0                         10.0                      2                       2  
1                         10.0                      2                       2  
2                         15.0                      2                       2  
3                         10.0                      2                       2  
4                         85.0                      2                       2  
...                        ...                    ...                     ...  
1208                      15.0                      2                       2  
1209                      15.0                      2                       2  
1210                      10.0                      2                       2  
1211                      10.0                      2                       2  
1212                      15.0                      2                       2  

[1213 rows x 7 columns]

In [ ]:
print(num_veh.isnull().any())

Eng Displ                             True
# Cyl                                False
Comb Unadj FE - Conventional Fuel    False
# Gears                              False
Max Ethanol % - Gasoline              True
Intake Valves Per Cyl                False
Exhaust Valves Per Cyl               False
dtype: bool


In [ ]:
#fill in any missing values with 0
num_veh_fill=num_veh.fillna(0)
print(num_veh_fill.isnull().any())


Eng Displ                            False
# Cyl                                False
Comb Unadj FE - Conventional Fuel    False
# Gears                              False
Max Ethanol % - Gasoline             False
Intake Valves Per Cyl                False
Exhaust Valves Per Cyl               False
dtype: bool


In [ ]:
X_train = num_veh_fill.drop('Comb Unadj FE - Conventional Fuel', axis=1)
y_train = num_veh_fill['Comb Unadj FE - Conventional Fuel']

In [ ]:
import numpy as np

In [ ]:
def test(X_train, y_train, n_estimators=150):
    rf = RandomForestRegressor(n_estimators=n_estimators, n_jobs=-1, oob_score=True)
    rf.fit(X_train, y_train)
    oob = rf.oob_score_
    print(f"OOB R^2 {oob:.5f} ")
    return rf, oob

In [ ]:
test(X_train,y_train,n_estimators=150)

OOB R^2 0.73875 


(RandomForestRegressor(n_estimators=150, n_jobs=-1, oob_score=True),
 0.7387493447650768)

### Part 2 - Normalize missing values

In this part you should: 
 - use Section 7.4 of the textbook as a guide
 - convert **all** representations of missing data to a **single** representation
 
#### Code (15 marks)

In [ ]:
import pandas.api.types

In [ ]:
veh['Eng Displ'].unique()

array([nan, 1.8, 3.5, 3.4, 2.5, 2. , 6.3, 6.2, 1.5, 3. , 1.4, 3.6, 6.7,
       4. , 1.6, 2.4, 6.5, 2.7, 5. , 3.7, 6. , 3.8, 5.7, 5.5, 5.9, 1. ,
       6.4, 4.7, 5.3, 2.8, 0.9, 3.3, 4.6, 4.4, 5.2, 4.3, 4.8, 3.9, 6.6,
       2.3, 8.4, 5.6, 6.8])

In [ ]:
veh['# Cyl'].unique()

array([ 4,  6, 12,  8,  3, 10,  5], dtype=int64)

In [ ]:
veh['Comb Unadj FE - Conventional Fuel'].unique()

array([32.8729, 41.5766, 42.3624, 29.3963, 25.4694, 27.9923, 25.6217,
       28.7955, 25.5194, 36.1046, 42.6092, 36.0247, 25.1277, 27.925 ,
       31.0325, 34.7404, 28.044 , 17.0002, 32.9334, 22.0201, 21.6821,
       43.1463, 31.0576, 29.8129, 27.723 , 33.7222, 30.4958, 47.715 ,
       18.7023, 40.434 , 33.1491, 20.076 , 29.3854, 21.0918, 17.4989,
       34.2453, 36.703 , 30.722 , 36.4494, 46.403 , 21.7662, 22.577 ,
       28.7377, 19.0572, 39.9942, 22.3336, 36.5144, 33.0335, 23.4292,
       16.2581, 25.263 , 21.2882, 34.2607, 19.7548, 31.9339, 34.3738,
       26.7662, 29.8923, 50.1953, 38.0027, 31.9024, 42.8024, 35.3153,
       34.7884, 46.6393, 40.0936, 35.8215, 33.9853, 25.6832, 27.3233,
       38.6615, 17.2204, 40.4893, 37.46  , 29.4792, 26.3559, 30.2755,
       28.5872, 34.858 , 31.4586, 26.2931, 37.7104, 25.5795, 26.1317,
       22.8351, 20.7441, 31.524 , 28.0618, 19.0009, 28.4872, 36.7729,
       31.5846, 31.3542, 57.4981, 47.9062, 29.6903, 15.9434, 40.7884,
       19.4738, 30.0

In [ ]:
veh['# Gears'].unique()

array([6, 8, 7, 9, 5, 1, 4], dtype=int64)

In [ ]:
veh['Max Ethanol % - Gasoline'].unique()

array([10., 15., 85., nan])

In [ ]:
veh['Intake Valves Per Cyl'].unique()

array([2, 1], dtype=int64)

In [ ]:
veh['Exhaust Valves Per Cyl'].unique()

array([2, 1], dtype=int64)

In [ ]:
veh['Trans Creeper Gear'].unique()

array(['N', 'Y'], dtype=object)

In [ ]:
veh['Unique Label?'].unique()

array(['N', 'Y', nan], dtype=object)

In [ ]:
veh['Air Aspiration Method Desc'].unique()

array(['Naturally Aspirated', 'none given', 'Turbocharged',
       'Supercharged', 'Turbocharged+Supercharged'], dtype=object)

In [ ]:
veh['Fuel Metering Sys Desc'].unique()

array(['Multipoint/sequential fuel injection',
       'Spark Ignition Direct Injection', '@@@@@',
       'Spark Ignition direct & ported injection',
       'Common Rail Direct Diesel Injection',
       'Direct Diesel Injection (non-common rail)'], dtype=object)

In [ ]:
veh['Cyl Deact?'].unique()

array(['N', '   ', nan, 'Y'], dtype=object)

In [ ]:
from pandas.api.types import is_float_dtype,is_object_dtype
def veh_normalize(veh):
    for col in veh.columns:
        if  is_object_dtype(veh[col]) or is_float_dtype(veh[col]) :
            veh[col] = veh[col].fillna(np.nan)
            veh[col] = veh[col].replace('none given', np.nan)
            veh[col] = veh[col].replace('@@@@@', np.nan)
            veh[col] = veh[col].replace('', np.nan)

In [ ]:
veh_normalize(veh)

#### Question (5 marks)

Note here all the different ways missing data was represented in the data.   

**Enter your answer here:**

### Part 3 - Categorical features

In this part you should: 
 - use Section 7.5.1 as a guide
 - only use ordinal encoding 
 - convert **all** non-numeric features to numeric 
 - handle any missing values
 
#### Code (25 marks)

In [ ]:
non_num_veh = veh.select_dtypes(exclude=['number'])
non_num_veh

Trans Creeper Gear Unique Label? Air Aspiration Method Desc  \
0                     N             N        Naturally Aspirated   
1                     N             N                        NaN   
2                     N             N                        NaN   
3                     N             N                        NaN   
4                     N             N        Naturally Aspirated   
...                 ...           ...                        ...   
1208                  N             N                        NaN   
1209                  N             N                        NaN   
1210                  N             N        Naturally Aspirated   
1211                  N             N                        NaN   
1212                  N             N        Naturally Aspirated   

                        Fuel Metering Sys Desc Cyl Deact?  
0         Multipoint/sequential fuel injection          N  
1              Spark Ignition Direct Injection          N  
2         Multipoint/sequential fuel injection             
3              Spark Ignition Direct Injection             
4         Multipoint/sequential fuel injection          N  
...                                        ...        ...  
1208  Spark Ignition direct & ported injection        NaN  
1209  Spark Ignition direct & ported injection          N  
1210           Spark Ignition Direct Injection          N  
1211                                       NaN        NaN  
1212      Multipoint/sequential fuel injection        NaN  

[1213 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import  OrdinalEncoder
ordinal = OrdinalEncoder()
veh['Air Aspiration Method Desc'] = ordinal.fit_transform(veh[['Air Aspiration Method Desc']])
veh['Cyl Deact?'] = ordinal.fit_transform(veh[['Cyl Deact?']])
veh['Fuel Metering Sys Desc'] = ordinal.fit_transform(veh[['Fuel Metering Sys Desc']])
veh['Trans Creeper Gear'] = ordinal.fit_transform(veh[['Trans Creeper Gear']])
veh['Unique Label?'] = ordinal.fit_transform(veh[['Unique Label?']])


In [ ]:
#from pandas.api.types import is_categorical_dtype
#def veh_obj_to_cat(veh):
    #for col in veh.columns:
        #if is_object_dtype(veh[col]) or is_float_dtype(veh[col]):
            #veh[col] = veh[col].astype('category').cat.as_ordered()
            

#def veh_cat_to_ordinal(veh):
    #for col in veh.columns:
        #if is_categorical_dtype(veh[col]):
            #veh[col] = veh[col].cat.codes + 1

In [ ]:
#veh_obj_to_cat(veh)

In [ ]:
#veh_cat_to_ordinal(veh)

In [ ]:
veh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Eng Displ                          845 non-null    float64
 1   # Cyl                              1213 non-null   int64  
 2   Comb Unadj FE - Conventional Fuel  1213 non-null   float64
 3   # Gears                            1213 non-null   int64  
 4   Max Ethanol % - Gasoline           1187 non-null   float64
 5   Intake Valves Per Cyl              1213 non-null   int64  
 6   Exhaust Valves Per Cyl             1213 non-null   int64  
 7   Trans Creeper Gear                 1213 non-null   float64
 8   Unique Label?                      1136 non-null   float64
 9   Air Aspiration Method Desc         687 non-null    float64
 10  Fuel Metering Sys Desc             841 non-null    float64
 11  Cyl Deact?                         985 non-null    float

### Part 4 - Numeric features

In this part you should: 
 - use Section 7.5.2 as a guide
 - handle any missing values
 
#### Code (30 marks)

In [ ]:
print(veh.isnull().any())

Eng Displ                             True
# Cyl                                False
Comb Unadj FE - Conventional Fuel    False
# Gears                              False
Max Ethanol % - Gasoline              True
Intake Valves Per Cyl                False
Exhaust Valves Per Cyl               False
Trans Creeper Gear                   False
Unique Label?                         True
Air Aspiration Method Desc            True
Fuel Metering Sys Desc                True
Cyl Deact?                            True
dtype: bool


In [ ]:
def fix_missing_num(veh, colname):
    veh[colname] = pd.isnull(veh[colname])
    veh[colname].fillna(veh[colname].median(), inplace=True)

In [ ]:
fix_missing_num(veh,'Eng Displ')
fix_missing_num(veh,'Max Ethanol % - Gasoline')
fix_missing_num(veh,'Unique Label?')
fix_missing_num(veh,'Air Aspiration Method Desc')
fix_missing_num(veh,'Fuel Metering Sys Desc')
fix_missing_num(veh,'Cyl Deact?')

In [ ]:
print(veh.isnull().any())

Eng Displ                            False
# Cyl                                False
Comb Unadj FE - Conventional Fuel    False
# Gears                              False
Max Ethanol % - Gasoline             False
Intake Valves Per Cyl                False
Exhaust Valves Per Cyl               False
Trans Creeper Gear                   False
Unique Label?                        False
Air Aspiration Method Desc           False
Fuel Metering Sys Desc               False
Cyl Deact?                           False
dtype: bool


### Part 5 - Create and evaluate a final model

In this part you should:
 - create and evaluate a model using all the features after processing them in Parts 2, 3, and 4 above 

#### Code (10 marks)

In [ ]:
X = veh.drop('Comb Unadj FE - Conventional Fuel', axis=1)
y = veh['Comb Unadj FE - Conventional Fuel']

NameError: name 'veh' is not defined

#### Questions (5 marks)

Provide answers to the following:
 1. calculate the percent difference between the results of Part 1 and Part 5 (make sure you are using the correct formula for percent difference) 
 2. based on the percent difference, state whether or not the results of Part 5 are an improvement over the results of Part 1

**Enter your answers here:**